### ISSUE TITLE
No reponse through ros2control position controller

### ISSUE THREAD

**Issue by henryliuliuliu** [cyberbotics/webots_ros2#372]
**Describe the Bug**
I am trying to use ros2control to control the robot in the webots, I successful control it through velocity and effort control, but when I try to use position controller, the robot does not move. 
I think the ros2control node is started correctly, as shown in the following picture. 
![image](https://user-images.githubusercontent.com/45789865/149401178-d4d10b99-4901-45c8-a668-2d3a9f70ccb4.png)
This is my yaml file for ros2webots:

```
controller_manager:
  ros__parameters:
    update_rate: 100 # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    joint0_position_controller:
      type: position_controllers/JointGroupPositionController

    joint0_velocity_controller:
      type: velocity_controllers/JointGroupVelocityController

    joint0_effort_controller:
      type: effort_controllers/JointGroupEffortController
    
    joint1_position_controller:
      type: position_controllers/JointGroupPositionController

    joint1_velocity_controller:
      type: velocity_controllers/JointGroupVelocityController

    joint1_effort_controller:
      type: effort_controllers/JointGroupEffortController

    group_position_controller:
      type: position_controllers/JointGroupPositionController

    group_velocity_controller:
      type: velocity_controllers/JointGroupVelocityController

    group_effort_controller:
      type: effort_controllers/JointGroupEffortController

joint0_position_controller:
  ros__parameters:
    joints:
      - motor1

joint0_velocity_controller:
  ros__parameters:
    joints:
      - motor1

joint0_effort_controller:
  ros__parameters:
    joints:
      - motor1

joint1_position_controller:
  ros__parameters:
    joints:
      - motor2

joint1_velocity_controller:
  ros__parameters:
    joints:
      - motor2

joint1_effort_controller:
  ros__parameters:
    joints:
      - motor2

group_position_controller:
  ros__parameters:
    joints:
      - motor1
      - motor2

group_velocity_controller:
  ros__parameters:
    joints:
      - motor1
      - motor2

group_effort_controller:
  ros__parameters:
    joints:
      - motor1
      - motor2
```

Below is my  urdf for my world file.
`
<?xml version="1.0" ?>
<robot name="singleleg">
    <webots>
        

        

        

        

        <plugin type="webots_ros2_control::Ros2Control" />
    </webots>

    <ros2_control name="WebotsControl" type="system">
        <hardware>
            <plugin>webots_ros2_control::Ros2ControlSystem</plugin>
        </hardware>
        <joint name="motor1">
            <state_interface name="position"/>
            <state_interface name="velocity"/>
            <state_interface name="effort"/>

            <command_interface name="position"/>
            <command_interface name="velocity"/>
            <command_interface name="effort"/>
        </joint>
        <joint name="motor2">
            <state_interface name="position"/>
            <state_interface name="velocity"/>
            <state_interface name="effort"/>

            <command_interface name="position"/>
            <command_interface name="velocity"/>
            <command_interface name="effort"/>
        </joint>
    </ros2_control>
</robot>

`
I cannot figure out where is the mistake? Btw, I tried to control it through controller of webots instead of using ros2control, then setPosition function works pretty well. 

Thanks for your time.
