### ISSUE TITLE
webots_ros2_turtlebot TF-Tree is split

### ISSUE THREAD

**Issue by janx8r** [cyberbotics/webots_ros2#401]
**Describe the Bug**
After launching robot_launch.py in webots_ros2_turtlebot the transformation tree is split.
This leads to the fact that the navigation does not work, because the sensor data of the lidar cannot be transformed to the odometry.
Apparently, the transformations between the frames 'base_link' and 'LDS-01' are missing, among others:
![frames](https://user-images.githubusercontent.com/95029851/153907825-c436d4b5-feec-4038-b5a6-27fdbea0b6b9.png)
If I add the missing transforms with static_transform_publisher in robot_launch.py, everything works.
I have the same problem with webots_ros2_tiago.

**Steps to Reproduce**
1. install Webots R-2022a (I have tried the debian and the tarball installation)
2. webots_ros2 clone and build:
    ````mkdir test_workspace
    cd test_workspace
    mkdir src
    cd src
    git clone --recursive https://github.com/cyberbotics/webots_ros2.git
    cd ..
    colcon build
    source install/local_setup.bash````
3. launch webots_ros2_turtlebot:
    ````ros2 launch webots_ros2_turtlebot robot_launch.py````
4. show the TF-Tree on a new terminal:
    ````ros2 run rqt_tf_tree rqt_tf_tree --force-discover````

**Expected behavior**
The tree should be connected in one piece so that the transformations between all frames can be calculated.
It should look like this in full (from @BenjaminHug8  in the Discord channel):
[frames.pdf](https://github.com/cyberbotics/webots_ros2/files/8062497/frames.pdf)

**Affected Packages**
List of affected packages:
  - webots_ros2_turtlebot
  - webots_ros2_tiago
  - probably more robot packages that are not yet tested


**System**
 - Webots Version: R-2022a
 - ROS Version: galactic
 - Operating System: Ubuntu 20.04
 - Graphics Card: NVIDIA Corporation GF108GLM [NVS 5200M]


**Additional context**
My outputs from webots_ros2_turtlebot:
````
jan@jan-laptop:~/ros2_test_ws$ ros2 launch webots_ros2_turtlebot robot_launch.py
[INFO] [launch]: All log files can be found below /home/jan/.ros/log/2022-02-14-17-27-01-907517-jan-laptop-86755
[INFO] [launch]: Default logging verbosity is set to INFO
[INFO] [spawner.py-1]: process started with pid [86757]
[INFO] [spawner.py-2]: process started with pid [86759]
[INFO] [webots-3]: process started with pid [86761]
[INFO] [robot_state_publisher-4]: process started with pid [86763]
[INFO] [driver-5]: process started with pid [86765]
[INFO] [static_transform_publisher-6]: process started with pid [86769]
[driver-5] Cannot open file: /tmp/webots-86761-HNGQX4/WEBOTS_SERVER (retry count 1)
[static_transform_publisher-6] [INFO] [1644856022.536536500] [static_transform_publisher_uw8YMyY3at2XRYQe]: Spinning until killed publishing transform from 'base_link' to 'base_footprint'
[robot_state_publisher-4] [INFO] [1644856022.541359329] [robot_state_publisher]: got segment 
[spawner.py-2] [INFO] [1644856022.821224693] [spawner_diffdrive_controller]: Waiting for /controller_manager services
[spawner.py-1] [INFO] [1644856022.840007177] [spawner_joint_state_broadcaster]: Waiting for /controller_manager services
[driver-5] Cannot open file: /tmp/webots-86761-HNGQX4/WEBOTS_SERVER (retry count 2)
[driver-5] Cannot open file: /tmp/webots-86761-HNGQX4/WEBOTS_SERVER (retry count 3)
[spawner.py-2] [INFO] [1644856024.836095716] [spawner_diffdrive_controller]: Waiting for /controller_manager services
[spawner.py-1] [INFO] [1644856024.855167190] [spawner_joint_state_broadcaster]: Waiting for /controller_manager services
[driver-5] Cannot open file: /tmp/webots-86761-HNGQX4/WEBOTS_SERVER (retry count 4)
[driver-5] Cannot open file: /tmp/webots-86761-HNGQX4/WEBOTS_SERVER (retry count 5)
[spawner.py-2] [INFO] [1644856026.847329130] [spawner_diffdrive_controller]: Waiting for /controller_manager services
[spawner.py-1] [INFO] [1644856026.866124079] [spawner_joint_state_broadcaster]: Waiting for /controller_manager services
[driver-5] Cannot open file: /tmp/webots-86761-HNGQX4/WEBOTS_SERVER (retry count 6)
[driver-5] Cannot open file: /tmp/webots-86761-HNGQX4/WEBOTS_SERVER (retry count 7)
[spawner.py-2] [INFO] [1644856028.859561341] [spawner_diffdrive_controller]: Waiting for /controller_manager services
[spawner.py-1] [INFO] [1644856028.878329833] [spawner_joint_state_broadcaster]: Waiting for /controller_manager services
[driver-5] Cannot open file: /tmp/webots-86761-HNGQX4/WEBOTS_SERVER (retry count 8)
[driver-5] Cannot open file: /tmp/webots-86761-HNGQX4/WEBOTS_SERVER (retry count 9)
[spawner.py-2] [INFO] [1644856030.871632009] [spawner_diffdrive_controller]: Waiting for /controller_manager services
[spawner.py-1] [INFO] [1644856030.889848505] [spawner_joint_state_broadcaster]: Waiting for /controller_manager services
[driver-5] Cannot open file: /tmp/webots-86761-HNGQX4/WEBOTS_SERVER (retry count 10)
[driver-5] Cannot open file: /tmp/webots-86761-HNGQX4/WEBOTS_SERVER (retry count 11)
[spawner.py-2] [INFO] [1644856032.882195255] [spawner_diffdrive_controller]: Waiting for /controller_manager services
[spawner.py-1] [INFO] [1644856032.899011849] [spawner_joint_state_broadcaster]: Waiting for /controller_manager services
[driver-5] Cannot open file: /tmp/webots-86761-HNGQX4/WEBOTS_SERVER (retry count 12)
[driver-5] Cannot open file: /tmp/webots-86761-HNGQX4/WEBOTS_SERVER (retry count 13)
[spawner.py-2] [INFO] [1644856034.893667797] [spawner_diffdrive_controller]: Waiting for /controller_manager services
[spawner.py-1] [INFO] [1644856034.910714478] [spawner_joint_state_broadcaster]: Waiting for /controller_manager services
[driver-5] Cannot open file: /tmp/webots-86761-HNGQX4/WEBOTS_SERVER (retry count 14)
[spawner.py-2] [INFO] [1644856036.904205888] [spawner_diffdrive_controller]: Waiting for /controller_manager services
[spawner.py-1] [INFO] [1644856036.923887707] [spawner_joint_state_broadcaster]: Waiting for /controller_manager services
[spawner.py-2] [INFO] [1644856038.915635867] [spawner_diffdrive_controller]: Waiting for /controller_manager services
[spawner.py-1] [INFO] [1644856038.935181647] [spawner_joint_state_broadcaster]: Waiting for /controller_manager services
[driver-5] [INFO] [1644856039.122609875] [controller_manager]: Loading controller 'diffdrive_controller'
[driver-5] [INFO] [1644856039.134607445] [controller_manager]: Setting use_sim_time=True for diffdrive_controller to match controller manager (see ros2_control#325 for details)
[spawner.py-2] [INFO] [1644856039.137004683] [spawner_diffdrive_controller]: Loaded diffdrive_controller
[driver-5] [INFO] [1644856039.138153725] [controller_manager]: Configuring controller 'diffdrive_controller'
[robot_state_publisher-4] Link LDS-01 had 6 children
[robot_state_publisher-4] Link solid(1) had 0 children
[robot_state_publisher-4] Link screw0 had 0 children
[robot_state_publisher-4] Link screw1 had 0 children
[robot_state_publisher-4] Link screw2 had 0 children
[robot_state_publisher-4] Link screw3 had 0 children
[robot_state_publisher-4] Link solid had 0 children
[robot_state_publisher-4] Link accelerometer had 0 children
[robot_state_publisher-4] Link compass had 0 children
[robot_state_publisher-4] Link gps had 0 children
[robot_state_publisher-4] Link gyro had 0 children
[robot_state_publisher-4] Link imu_link had 0 children
[robot_state_publisher-4] Link inertial_unit had 0 children
[robot_state_publisher-4] Link left wheel had 0 children
[robot_state_publisher-4] Link right wheel had 0 children
[robot_state_publisher-4] [INFO] [1644856039.227846326] [robot_state_publisher]: got segment LDS-01
[robot_state_publisher-4] [INFO] [1644856039.227905940] [robot_state_publisher]: got segment accelerometer
[robot_state_publisher-4] [INFO] [1644856039.227920572] [robot_state_publisher]: got segment base_link
[robot_state_publisher-4] [INFO] [1644856039.227932422] [robot_state_publisher]: got segment compass
[robot_state_publisher-4] [INFO] [1644856039.227943418] [robot_state_publisher]: got segment gps
[robot_state_publisher-4] [INFO] [1644856039.227954748] [robot_state_publisher]: got segment gyro
[robot_state_publisher-4] [INFO] [1644856039.227965519] [robot_state_publisher]: got segment imu_link
[robot_state_publisher-4] [INFO] [1644856039.227976144] [robot_state_publisher]: got segment inertial_unit
[robot_state_publisher-4] [INFO] [1644856039.227990219] [robot_state_publisher]: got segment left wheel
[robot_state_publisher-4] [INFO] [1644856039.228005115] [robot_state_publisher]: got segment right wheel
[robot_state_publisher-4] [INFO] [1644856039.228015889] [robot_state_publisher]: got segment screw0
[robot_state_publisher-4] [INFO] [1644856039.228026748] [robot_state_publisher]: got segment screw1
[robot_state_publisher-4] [INFO] [1644856039.228037199] [robot_state_publisher]: got segment screw2
[robot_state_publisher-4] [INFO] [1644856039.228047604] [robot_state_publisher]: got segment screw3
[robot_state_publisher-4] [INFO] [1644856039.228057943] [robot_state_publisher]: got segment solid
[robot_state_publisher-4] [INFO] [1644856039.228068337] [robot_state_publisher]: got segment solid(1)
[driver-5] [INFO] [1644856039.423904953] [plugin_node_example]: PluginExample: The init() method is called and new node created
[driver-5] [INFO] [1644856039.424563873] [plugin_node_example]: PluginExample: 
[driver-5] [INFO] [1644856039.425178212] [plugin_node_example]:   - properties: {'parameterExample': 'someValue'}
[driver-5] [INFO] [1644856039.425808927] [plugin_node_example]:   - basic timestep: 20
[driver-5] [INFO] [1644856039.426470094] [plugin_node_example]:   - robot name: TurtleBot3Burger
[driver-5] [INFO] [1644856039.427169061] [plugin_node_example]:   - is robot? True
[driver-5] [INFO] [1644856039.429766820] [plugin_node_example]: PluginExample: Publisher created
[driver-5] [INFO] [1644856039.484141230] [controller_manager]: Loading controller 'joint_state_broadcaster'
[spawner.py-2] [INFO] [1644856039.485268254] [spawner_diffdrive_controller]: Configured and started diffdrive_controller
[driver-5] [INFO] [1644856039.493991401] [controller_manager]: Setting use_sim_time=True for joint_state_broadcaster to match controller manager (see ros2_control#325 for details)
[spawner.py-1] [INFO] [1644856039.504156426] [spawner_joint_state_broadcaster]: Loaded joint_state_broadcaster
[driver-5] [INFO] [1644856039.505930009] [controller_manager]: Configuring controller 'joint_state_broadcaster'
[spawner.py-1] [INFO] [1644856039.538182063] [spawner_joint_state_broadcaster]: Configured and started joint_state_broadcaster
[spawner.py-2] /opt/ros/galactic/lib/controller_manager/spawner.py:204: DeprecationWarning: 'spawner.py' is deprecated, please use 'spawner' (without .py extension)
[spawner.py-2]   warnings.warn(
[INFO] [spawner.py-2]: process has finished cleanly [pid 86759]
[spawner.py-1] /opt/ros/galactic/lib/controller_manager/spawner.py:204: DeprecationWarning: 'spawner.py' is deprecated, please use 'spawner' (without .py extension)
[spawner.py-1]   warnings.warn(
[INFO] [spawner.py-1]: process has finished cleanly [pid 86757]
````

`echo $PYTHONPATH`:
````/home/jan/ros2_test_ws/install/webots_ros2/lib/python3.8/site-packages:
/home/jan/ros2_test_ws/install/webots_ros2_universal_robot/lib/python3.8/site-packages:
/home/jan/ros2_test_ws/install/webots_ros2_turtlebot/lib/python3.8/site-packages:
/home/jan/ros2_test_ws/install/webots_ros2_tiago/lib/python3.8/site-packages:
/home/jan/ros2_test_ws/install/webots_ros2_tests/lib/python3.8/site-packages:
/home/jan/ros2_test_ws/install/webots_ros2_tesla/lib/python3.8/site-packages:
/home/jan/ros2_test_ws/install/webots_ros2_mavic/lib/python3.8/site-packages:
/home/jan/ros2_test_ws/install/webots_ros2_epuck/lib/python3.8/site-packages:
/home/jan/ros2_test_ws/install/webots_ros2_driver/lib/python3.8/site-packages:
/home/jan/ros2_test_ws/install/webots_ros2_core/lib/python3.8/site-packages:
/home/jan/ros2_test_ws/install/webots_ros2_msgs/lib/python3.8/site-packages:
/home/jan/ros2_test_ws/install/webots_ros2_importer/lib/python3.8/site-packages:
/opt/ros/galactic/lib/python3.8/site-packages:
/usr/local/webots/lib/controller/python38:
````

`echo $WEBOTS_HOME`: 
````/usr/local/webots````

`echo $LD_LIBRARY_PATH`: 
````
/home/jan/ros2_test_ws/install/webots_ros2_control/lib:
/home/jan/ros2_test_ws/install/webots_ros2_driver/lib:
/home/jan/ros2_test_ws/install/webots_ros2_msgs/lib:
/usr/lib/x86_64-linux-gnu/gazebo-11/plugins:
/opt/ros/galactic/opt/yaml_cpp_vendor/lib:
/opt/ros/galactic/opt/rviz_ogre_vendor/lib:
/opt/ros/galactic/lib/x86_64-linux-gnu:
/opt/ros/galactic/lib:
/usr/local/webots/lib/controller:
````

`ros2 topic list`:
````
/TurtleBot3Burger/gps
/TurtleBot3Burger/gps/speed
/TurtleBot3Burger/gps/speed_vector
/clock
/cmd_vel
/custom_time
/dynamic_joint_states
/imu
/joint_states
/odom
/parameter_events
/robot_description
/rosout
/scan
/scan/point_cloud
/tf
/tf_static
````
`ros2 topic echo /joint_states`:
````
header:
  stamp:
    sec: 556
    nanosec: 940000000
  frame_id: ''
name:
- left wheel motor
- right wheel motor
- LDS-01_secondary_motor
- LDS-01_main_motor
position:
- 0.0
- 0.0
- 0.0
- 0.0
velocity:
- .nan
- .nan
- 0.0
- 0.0
effort:
- .nan
- .nan
- 0.0
- 0.0
````

`ros2 topic echo /robot_description`:
````
[nothing]
````

`ros2 topic echo /tf`:
````
transforms:
- header:
    stamp:
      sec: 717
      nanosec: 860000000
    frame_id: LDS-01
  child_frame_id: solid(1)
  transform:
    translation:
      x: -0.046
      y: 0.02
      z: -0.01
    rotation:
      x: -2.5000197874904343e-06
      y: -6.99999293290575e-06
      z: 0.9999999999683797
      w: 2.82677739658369e-06
- header:
    stamp:
      sec: 717
      nanosec: 860000000
    frame_id: LDS-01
  child_frame_id: solid
  transform:
    translation:
      x: -0.046
      y: 0.01
      z: -0.01
    rotation:
      x: -2.5000197874904343e-06
      y: -6.99999293290575e-06
      z: 0.9999999999683797
      w: 2.82677739658369e-06
- header:
    stamp:
      sec: 717
      nanosec: 860000000
    frame_id: base_link
  child_frame_id: left wheel
  transform:
    translation:
      x: 0.0
      y: 0.08
      z: 0.033
    rotation:
      x: 0.7071048476552318
      y: 1.6700949020953548e-07
      z: 0.7071087147084275
      w: -2.4164686283356666e-06
- header:
    stamp:
      sec: 717
      nanosec: 860000000
    frame_id: base_link
  child_frame_id: right wheel
  transform:
    translation:
      x: 0.0
      y: -0.08
      z: 0.033
    rotation:
      x: 0.0
      y: -0.7071066656470943
      z: 0.0
      w: 0.7071068967259818
---
transforms:
- header:
    stamp:
      sec: 717
      nanosec: 880000000
    frame_id: odom
  child_frame_id: base_link
  transform:
    translation:
      x: 0.0
      y: 0.0
      z: 0.0
    rotation:
      x: 0.0
      y: 0.0
      z: 0.0
      w: 1.0
````
